Repository Dragonsight91/Demon-Overlord, pull requests merged in 2020-12, with the labels that each got.

#56 Goodbye demons lounge
  DemonOverlord/config/special/chats.json
Labels: update

#58 Database
  .dockerignore
  .gitignore
  CODE_OF_CONDUCT.md
  DemonOverlord/config/config.json
  DemonOverlord/config/db_template.json
  DemonOverlord/config/interactions.json
  DemonOverlord/config/json_templates/database/column_obj.json
  DemonOverlord/config/json_templates/database/table_obj.json
  DemonOverlord/config/json_templates/help/actions.json
  DemonOverlord/config/json_templates/help/category.json
  DemonOverlord/config/json_templates/help/command.json
  DemonOverlord/config/json_templates/help/params.json
  DemonOverlord/config/json_templates/interactions/alone_interaction.json
  DemonOverlord/config/json_templates/interactions/combine_interactions.json
  DemonOverlord/config/json_templates/interactions/social_interactions.json
  DemonOverlord/core/demonoverlord.py
  DemonOverlord/core/modules/interactions.py
  DemonOverlord/core/modules/izzy.py
  DemonOverlord/core/util/command.py
  DemonOverlord/core/util/config.py
  DemonOverlord/core/util/game_responses.py
  DemonOverlord/core/util/limit.py
  DemonOverlord/core/util/logger.py
  Procfile
  README.md
  docker/README.md
  docker/deploy-setup.sh
  docker/docker-compose.yaml
  run.py
  runtime.txt
Labels: bug, enhancement, update

#60 Steam integration done
  .gitignore
  DemonOverlord/config/db_template.json
  DemonOverlord/config/interactions.json
  DemonOverlord/core/demonoverlord.py
  DemonOverlord/core/modules/interactions.py
  DemonOverlord/core/util/api.py
  DemonOverlord/core/util/config.py
  DemonOverlord/core/util/logger.py
  requirements.txt
  run.py
Labels: bug, enhancement, update

#63 Bot permissions
  DemonOverlord/core/modules/izzy.py
  DemonOverlord/core/util/command.py
  DemonOverlord/core/util/responses.py
Labels: enhancement, update

#64 Welcome message
  .gitignore
  DemonOverlord/config/config.json
  DemonOverlord/config/db_template.json
  DemonOverlord/core/demonoverlord.py
  DemonOverlord/core/modules/interactions.py
  DemonOverlord/core/modules/welcome.py
  DemonOverlord/core/util/api.py
  DemonOverlord/core/util/command.py
  DemonOverlord/core/util/config.py
  DemonOverlord/core/util/limit.py
  DemonOverlord/core/util/logger.py
  DemonOverlord/core/util/responses.py
  DemonOverlord/core/util/services.py
  docker/Dockerfile
  requirements.txt
Labels: enhancement, update
