Repository Dragonsight91/Demon-Overlord, pull requests merged in 2021-01, with the labels that each got.

#65 Some more logging statements and replacement of the `chat` command with `channels` command
  DemonOverlord/config/special/chats.json
  DemonOverlord/config/special/minecraft.json
  DemonOverlord/core/demonoverlord.py
  DemonOverlord/core/modules/channel.py
  DemonOverlord/core/modules/chat.py
  DemonOverlord/core/modules/minecraft.py
  DemonOverlord/core/util/command.py
  DemonOverlord/core/util/config.py
Labels: enhancement, update

#76 Bump discord.py to 1.6
  docker/Dockerfile
  requirements.txt
Labels: dependencies, update

#74 Small bug fixes
  DemonOverlord/config/interactions.json
  DemonOverlord/core/modules/interactions.py
Labels: bug, update

#78 [TODO/BUGFIX] Interactions
  .gitignore
  DemonOverlord/config/config.json
  DemonOverlord/config/interactions.json
  DemonOverlord/config/json_templates/interactions/social_interactions.json
  DemonOverlord/core/modules/interactions.py
Labels: TODO, bug, feature, update

#79 [BUGFIX] Fixed double interaction (eat both in single and combine)
  DemonOverlord/config/interactions.json
Labels: bug, update
